#端口号配置
server:
  port: 8089 #数据库连接配置
  servlet:
    context-path: /system
    session:
      timeout: 3600s #设置会话的超时时间

spring:
  profiles:
    active:
      common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/property-manage-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true& serverTimezone=Asia/Shanghai
    username: root
    password: 12345
  jackson:
    time-zone: Asia/Shanghai


mybatis-plus:
  mapperLocations: classpath:xml/*.xml

jackson:
  time-zone: Asia/Shanghai

logging:
  level:
    root: warn
    com.jian.propertymanagesystem.mapper: trace
  pattern:
    console: '%p%m%n'

